version = 1

[*]
jinja = true
log-verbosity = 4
flash-attn = on
models-max = 1
ctx-size = 65536
n-gpu-layers = 999
parallel = 1

cache-type-k = q8_0
cache-type-v = q8_0
mlock = true
no-mmap = true




[gemma-4-26B-A4B-it]
# curl -L https://huggingface.co/unsloth/gemma-4-26B-A4B-it-qat-GGUF/resolve/main/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf -o gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
# curl -L https://huggingface.co/unsloth/gemma-4-26B-A4B-it-qat-GGUF/resolve/main/MTP/gemma-4-26B-A4B-it-Q8_0-MTP.gguf -o gemma-4-26B-A4B-it-Q8_0-MTP.gguf
model = ~/models/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
model-draft = ~/models/gemma-4-26B-A4B-it-Q8_0-MTP.gguf

ctx-size = 262144
n-cpu-moe = 30

spec-type = draft-mtp
spec-draft-ngl = 999
spec-draft-n-max = 4
spec-draft-p-min = 0.7

reasoning = on
reasoning-budget = 8192



[gemma-4-12B-it]
# curl -L https://huggingface.co/unsloth/gemma-4-12B-it-qat-GGUF/resolve/main/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf -o gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
# curl -L https://huggingface.co/unsloth/gemma-4-12B-it-qat-GGUF/resolve/main/MTP/gemma-4-12B-it-Q8_0-MTP.gguf -o gemma-4-12B-it-Q8_0-MTP.gguf
model = ~/models/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
model-draft = ~/models/gemma-4-12B-it-Q8_0-MTP.gguf

ctx-size = 65536

spec-type = draft-mtp
spec-draft-ngl = 999
spec-draft-n-max = 4
spec-draft-p-min = 0.7

reasoning = on
reasoning-budget = 8192


[Qwen3.6-35B-A3B]
# curl -L https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf -o Qwen3.6-35B-A3B-MTP-UD-Q4_K_XL.gguf
model = ~/models/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf

ctx-size = 262144
n-cpu-moe = 40

spec-type = draft-mtp
spec-draft-ngl = 999
spec-draft-n-max = 3
spec-draft-p-min = 0.7

reasoning = on
reasoning-budget = 8192
reasoning-budget-message = "My reasoning budget is exhausted, but I have enough information to answer directly now.</think>"

temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

chat-template-kwargs = {"preserve_thinking":false}





